# Generated by Django 6.0.3 on 2026-04-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emprendedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, verbose_name="Nombre")),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("CE", "Cédula de Extranjería"),
                            ("NIT", "Número de Identificación Tributaria"),
                        ],
                        max_length=3,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "documento",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Documento"
                    ),
                ),
                (
                    "actividad_economica",
                    models.CharField(
                        max_length=100, verbose_name="Actividad Economica"
                    ),
                ),
                ("sector", models.CharField(max_length=100, verbose_name="Sector")),
                ("telefono", models.CharField(max_length=20, verbose_name="Teléfono")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Correo Electrónico"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(max_length=200, verbose_name="Dirección"),
                ),
            ],
        ),
    ]
