# Generated by Django 6.0.3 on 2026-04-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emprendedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("CE", "Cédula de Extranjería"),
                        ],
                        max_length=2,
                    ),
                ),
                ("documento", models.CharField(max_length=15, unique=True)),
                ("actividad_economica", models.CharField(max_length=100)),
                ("sector", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("direccion", models.CharField(max_length=200)),
            ],
        ),
    ]
