# Generated by Django 6.0.3 on 2026-04-08 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emprendedor",
            old_name="actividad_economica",
            new_name="actividad",
        ),
    ]
