# Generated by Django 6.0.3 on 2026-05-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_actividad_economica_emprendedor_actividad"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del Programa"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripción del Programa"),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de Inicio")),
                ("fecha_fin", models.DateField(verbose_name="Fecha de Fin")),
                ("cupos", models.IntegerField(verbose_name="Cupos Disponibles")),
            ],
        ),
        migrations.AlterField(
            model_name="emprendedor",
            name="actividad",
            field=models.CharField(max_length=100, verbose_name="Actividad Económica"),
        ),
        migrations.AlterField(
            model_name="emprendedor",
            name="nombre",
            field=models.CharField(max_length=50, verbose_name="Nombre completo"),
        ),
        migrations.AlterField(
            model_name="emprendedor",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("CC", "Cédula de Ciudadanía"),
                    ("CE", "Cédula de Extranjería"),
                ],
                max_length=2,
                verbose_name="Tipo",
            ),
        ),
    ]
