# Generated by Django 6.0.3 on 2026-05-08 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_programas_alter_emprendedor_actividad_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emprendedor",
            name="programa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.programas",
            ),
        ),
    ]
