# Generated by Django 6.0.3 on 2026-05-08 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_emprendedor_programa"),
    ]

    operations = [
        migrations.CreateModel(
            name="observaciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Observación"
                    ),
                ),
                ("observacion", models.TextField(verbose_name="Observación")),
                (
                    "emprendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.emprendedor",
                    ),
                ),
                (
                    "programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.programas"
                    ),
                ),
            ],
        ),
    ]
